# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: OyBcSt - NOAA RESTORE
author: Lisa L. Lowe, and The Jupyter Book Community
logo: oybcst_gh.png 
copyright                   : "2023"  # Copyright year to be placed in the footer

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

#references
bibtex_bibfiles:
    - references.bib

bibtex_reference_style: 
    - author_year

#latex-style math
#parse: 
#  myst_enable_extensions:
#  # don't forget to list any other extensions you want enabled,
#  # including those that are enabled by default!
#  - amsmath

mathjax_path: 
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Information about where the book exists on the web
repository:
  url: https://github.com/oybcst/oybcst.github.io  # Online location of your book
  path_to_book: /  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  favicon: oybcst_gh.png 

sphinx:
  html_context:
    default_mode: dark 
